/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Product = {
  /**
   * @format int64
   */
  id: number;
  name?: string;
  description?: string;
  /**
   * @format int64
   */
  price?: number;
  picture?: string;
};
