spring:
  application:
    name: shoppingCart
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shopping
    username: sa
    password: password
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none